#!/data/data/com.termux/files/usr/bin/sh
# termux-services definition for the shared tunnel.
exec /data/data/com.termux/files/usr/bin/cloudflared tunnel --config /data/data/com.termux/files/home/.cloudflared/config.yml run
